### ISSUE TITLE
Newlines get escaped (repeatedly)

### ISSUE THREAD

**Issue by bb-migration** [yougov/velociraptor#129]
Originally reported by: **Jason R. Coombs (Bitbucket: [jaraco](http://bitbucket.org/jaraco), GitHub: [jaraco](http://github.com/jaraco))**

----------------------------------------

I have a swarm with this config YAML:

```
email_notices:
- patterns: Gryphon
  template: |
    {event[title]} was deployed.
```

The email_notices.template is the Python string "{event[title]} was deployed\n".

However, immediately after swarming, the YAML looks like this:

```
email_notices:
- patterns: Gryphon
  template: '{event[title]} was deployed.

    '
```

If I then swarm the app using vr.cli, which invokes PATCH on the swarm, the config is again mutated:

```
email_notices:
- patterns: Gryphon
  template: '{event[title]} was deployed.\n'
```

If I swarm with the command line one more time, the newline is replaced with a literal `\n`:

```
email_notices:
- patterns: Gryphon
  template: '{event[title]} was deployed.\\n'
```

Thereafter, every swarm will get twice as many backslashes followed by an 'n'.

Except for the first mutation, the issue only occurs when using the command line, so this issue is probably another manifestation of #72.

----------------------------------------
- Bitbucket: https://bitbucket.org/yougov/velociraptor/issue/129

**Comment by lbolla** [comment]
Fixed in https://github.com/yougov/vr.server/commit/18d786eafaadc028774f7a05d03efe72c40d1b4b
