### ISSUE TITLE
Move project hosting to Github

### ISSUE THREAD

**Issue by bb-migration** [yougov/velociraptor#205]
Originally reported by: **Jason R. Coombs (Bitbucket: [jaraco](http://bitbucket.org/jaraco), GitHub: [jaraco](http://github.com/jaraco))**

---

I'd like to consider moving this project (and its subrepos) to git and Github. Any objections or concerns?

---
- Bitbucket: https://bitbucket.org/yougov/velociraptor/issue/205

**Comment by jaraco** [comment]
Given there weren't any concerns raised with the migration, I'm going to proceed. I'll remove the issues from BB and consider the migrated issues authoritative. I'll work out the Git repo hosting subsequently.

**Comment by lbolla** [comment]
Sorry I am late for the comment, but what are going to be the benefits of moving away from bitbucket?

**Comment by jaraco** [comment]
1. Everybody is leaving Mercurial behind, including YouGov, with Git reigning.
2. Github is by far the most dominant Git hosting service.
3. Github is the defacto host for YouGov Open Source repos in Git.
4. Github offers Travis-CI, which provides a much more friendly and capable integration solution than drone.io.
5. Github provides a superior workflow for managing issues, pull requests, etc.

**Comment by jaraco** [comment]
The main downside I forsee is that I'm unsure how well the 'subrepos' arrangement will translate to 'submodules', but I figure worst case we'll punt on submodules and just manage the submodules manually or through utility scripts in the parent repo.

**Comment by jaraco** [comment]
I've created the various repos and pushed the commits to them. I've begun cleanup on this repo and will begin work on the subrepos.

**Comment by jaraco** [comment]
I've updated the latest code to use [git submodules](https://git-scm.com/book/en/v2/Git-Tools-Submodules) and updated the developer docs to describe how to perform a checkout with them. We might consider adding additional hints about submodules as we figure out how they work.

**Comment by jaraco** [comment]
### Checklist

[x] Migrate issues
[x] Migrate code
[x] Update developer docs
[ ] Update ReadTheDocs
[ ] Update Drone.IO or enable Travis-CI

**Comment by lbolla** [comment]
Fair enough. Bitbucket supports git, too, though.
From my point of view, the biggest downside is to surprise contributors who adapted their workflow to bitbucket+hg: but given that the vast majority of contributors are YG's employees, I guess this is fine!

**Comment by jaraco** [comment]
This work is finally complete. I've updated all of the projects to use Travis-CI for running tests. To facilitate this transition, I also merged in the [jaraco skeleton](/jaraco/skeleton) to each of the submodules, which adds several features to these projects:

- automated deployment; tagged commits that pass on Python 3.5 (or 2.7 for projects not yet supporting Python 3) will be automatically released to PyPI (both sdist and wheel).
- Harmonized metadata.
- Use of setuptools_scm for version management and file tracking (saves need for MANIFEST.in).
- Tests run under tox. Simply invoke 'tox' in each project to invoke the tests. Invoke with `tox -e py27` or similar to invoke against a particular environment.
- Expanded test coverage, including doctests on all (viable) modules, which at the very least provides syntax and import checks on each module.

Moving to Travis added the following features:

- Slack notifications of failed and successful builds.
- Tests run against pull requests.
- Better test isolation (vr.server no longer relies on MongoDB on port 27017).
- Better platform coverage (it's trivially simple to test on Python 3 and 2.7).

All of this together means it should be much easier for others to make contributions to the projects and to cut releases rapidly and with minimal fuss (through the web even).

If you have any questions about these recent changes, do feel free to reply here, file a new ticket, or reach out on IRC/Slack.

All the best, Jason
