### ISSUE TITLE
Pages should have more specific titles

### ISSUE THREAD

**Issue by sd2k** [yougov/velociraptor#213]
Right now every page shares the same title ('Velociraptor') which makes it quite hard to tell which page is what in your browser history or if you have multiple tabs open. It would be nice if they had more useful titles, e.g. 

- New Swarm - Velociraptor
- Ingredients - Velociraptor
- vr_python_example - Swarm - Velociraptor

**Comment by lbolla** [comment]
Fixed in https://github.com/yougov/vr.server/commit/0bba79e
