### ISSUE TITLE
swarm config diffs contains ¶ character at the end of each line

### ISSUE THREAD

**Issue by amateja** [yougov/velociraptor#217]
In each swarm in **Versions** tab in **Diff** column are ¶ chars at the end of each line of config_yaml row. Could you have a look on that to see if it's an error or not?

**Comment by lbolla** [comment]
It's just the "newline" symbol used by "django-reversion's generate_patch_html" function that we use to generate a pretty diff of the changes.

**Comment by amateja** [comment]
It's not exactly ["newline" symbol](https://en.wiktionary.org/wiki/%C2%B6) and diff should show differences between two configs where none of those contains such symbol. Kinda misleading.

**Comment by lbolla** [comment]
The HTML symbol "&para;" is what's used by Google's `diff_match_patch` library (itself used by Django's `reversion`) to pretty-print a newline in HTML. See https://bitbucket.org/spookylukey/diff-match-patch/src/89225550f1af82beaa1278926305054170f6c6c5/python2/diff_match_patch/diff_match_patch.py?at=default&fileviewer=file-view-default#diff_match_patch.py-1073

So, the diff is highlighting all characters that are different in the 2 sets and it seems like the newline is one of them. We could use the usual diff format, rather then its pretty-printed HTML representation, but it's more verbose.
