### ISSUE TITLE
too much noise in events stream

### ISSUE THREAD

**Issue by pawciobiel** [yougov/velociraptor#223]

**Comment by jaraco** [comment]
@pawciobiel Can you elaborate? I believe the uptest events do show up in the event stream. Are you saying you'd like to see the output of each uptest in the event stream or in the event log (I think those are two different things)?  If so, that seems like a reasonable thing to have.

Probably the biggest challenge here may be if that output isn't persisted anywhere.

**Comment by pawciobiel** [comment]
So yes, the uptests do show up in event stream (under Events, on the main page)
but due to many projects being deployed in the same time, sometimes it's impossible to notice it.
So I was wondering if I could change the "Deployment Log" (/log/ page) which has a filter by username
so I could see all the events generated by my swarms.

**Comment by lbolla** [comment]
If it's a problem of "noise", I always wished the event stream was filtered to only show the events relative to the applications visible in the current dashboard: so one would define a dashboard with just the apps he is interested in and the event stream would show events related to those apps only.
Further filtering of the event stream would be nice, too.

**Comment by pawciobiel** [comment]
Yes. this is exactly what I need. Thanks!

**Comment by jaraco** [comment]
We have a private project too we call DeployNotifier, which will route these events to other systems (like IRC or New Relic) where they can be monitored separately. You may consider adapting that tool or copying its technique to pull select events off the queue and watch them.

One thing we'd considered doing in the vr.cli is to have it monitor the event stream for a given swarm or set of swarms, and invoke that behavior by default when dispatching some swarms.

**Comment by jaraco** [comment]
It occurs to me the deploy notifier should probably be an open-source package in the vr.* namespace.

**Comment by jaraco** [comment]
Today I did some work to strip out a lot of YouGov-specific content from the notifier, so it's in a state that could be open-sourced, but I'm going to have to leave it at that.

While I was doing that, I was reminded that our VR environment is configured to route VR events to pmxbot via https://github.com/jaraco/jaraco.pmxbot/blob/6beb1a7490785de6a6a5a84d669d9cba77c1cf9d/jaraco/pmxbot/http.py#L139, so perhaps that provides a suitably configurable stream for your needs.

**Comment by pawciobiel** [comment]
Wow! thanks a lot.

**Comment by lbolla** [comment]
I've pushed a fix for this in https://github.com/yougov/vr.server/commit/0144710fdf1ba601dfa3684c43ebe755d6041afa

**Comment by jaraco** [comment]
That's pretty awesome. !thanks lbolla.
